version: '3.7'
services:
  app:
    build: .
    ports:
      - "5050:8008"
    depends_on:
      - db
  db:
    image: kartoza/postgis
    environment:
      POSTGRES_PASSWORD: sbtemplate
      POSTGRES_USER: sbtemplate
      POSTGRES_DB: sbtemplate
    volumes:
      - ./db:/docker-entrypoint-initdb.d/


  migration:
    build:
      context: ./dj
    environment:
      - DB_HOST=db
      - DB_NAME=sbtemplate
      - DB_USER=sbtemplate
      - DB_PASS=sbtemplate
    depends_on:
      - db